# Generated by Django 5.1.2 on 2025-02-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at_order_refund_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Shipping fee at the time of order', max_digits=10),
        ),
    ]
