# Generated by Django 5.1.2 on 2024-12-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='status',
        ),
        migrations.AddField(
            model_name='return',
            name='items_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='return',
            name='return_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Return Approved'), ('received', 'Items Received'), ('rejected', 'Return Rejected'), ('completed', 'Return Completed')], default='pending', max_length=20),
        ),
    ]
