# Generated by Django 5.1.2 on 2025-01-01 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_image'),
        ('returns', '0003_alter_return_return_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.IntegerField(default=3, help_text='Number of days after delivery within which returns are accepted')),
                ('requires_receipt', models.BooleanField(default=True, help_text='Whether returns require original order confirmation')),
                ('allow_partial_returns', models.BooleanField(default=True, help_text='Allow returning part of an order')),
                ('restocking_fee_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage fee charged for returns', max_digits=5)),
                ('free_returns', models.BooleanField(default=True, help_text='Whether return shipping is free')),
                ('shipping_paid_by', models.CharField(choices=[('customer', 'Customer'), ('store', 'Store')], default='store', help_text='Who pays for return shipping', max_length=20)),
                ('return_instructions', models.TextField(blank=True, help_text='Instructions provided to customers for returns')),
            ],
            options={
                'verbose_name_plural': 'Return policies',
            },
        ),
        migrations.CreateModel(
            name='ProductReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returnable', models.BooleanField(default=True, help_text='Whether this product can be returned')),
                ('return_window_days', models.IntegerField(blank=True, help_text='Override global return window for this product', null=True)),
                ('restocking_fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Override global restocking fee for this product', max_digits=5, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special return instructions for this product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_policy', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'Product Return Policies',
            },
        ),
    ]
