# Generated by Django 5.1.2 on 2025-01-14 02:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at_order_refund_amount_and_more'),
        ('products', '0007_productimage_public_id_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('max_quantity_per_customer', models.PositiveIntegerField(default=1, help_text='Maximum quantity of each product per customer')),
                ('total_quantity_limit', models.PositiveIntegerField(blank=True, help_text='Total quantity available for the flash sale', null=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the sale is visible to customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flash_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qauntity_limit', models.PositiveIntegerField(blank=True, help_text='Maximum quantity available for this product in the sale', null=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='products.flashsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_entries', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(related_name='flash_sales', through='products.FlashSaleProduct', to='products.product'),
        ),
        migrations.CreateModel(
            name='FlashSalePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flash_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='products.flashsale')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['flash_sale', 'product'], name='products_fl_flash_s_0e8941_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleproduct',
            unique_together={('flash_sale', 'product')},
        ),
        migrations.AddIndex(
            model_name='flashsale',
            index=models.Index(fields=['status', 'start_time', 'end_time'], name='products_fl_status_8b330f_idx'),
        ),
        migrations.AddIndex(
            model_name='flashsalepurchase',
            index=models.Index(fields=['flash_sale', 'product', 'user'], name='products_fl_flash_s_974caf_idx'),
        ),
    ]
