# Generated by Django 5.1.2 on 2025-01-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_flashsaleproduct_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashsaleproduct',
            old_name='qauntity_limit',
            new_name='quantity_limit',
        ),
    ]
