# Generated by Django 5.1.2 on 2025-01-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_qauntity_limit_flashsaleproduct_quantity_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashsaleproduct',
            name='original_price',
        ),
    ]
