# Generated by Django 5.1.2 on 2025-01-09 23:42

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_cancelled_at_order_refund_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('thread_id', models.CharField(blank=True, help_text='ID for grouping related emails', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('read', 'Read'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_emails', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='email_attachments')),
                ('filename', models.CharField(max_length=255)),
                ('public_id', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=300)),
                ('file_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customer_support.customeremail')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_count', models.IntegerField(default=0)),
                ('response_time', models.DurationField(blank=True, help_text='Time taken to respond to customer', null=True)),
                ('bounced', models.BooleanField(default=False)),
                ('bounce_reason', models.TextField(blank=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='customer_support.customeremail')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=dict, help_text='Variables that can be used in the template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='customeremail',
            index=models.Index(fields=['thread_id'], name='customer_su_thread__f33739_idx'),
        ),
        migrations.AddIndex(
            model_name='customeremail',
            index=models.Index(fields=['created_at'], name='customer_su_created_beb96d_idx'),
        ),
        migrations.AddIndex(
            model_name='customeremail',
            index=models.Index(fields=['status'], name='customer_su_status_2925f6_idx'),
        ),
    ]
