# Generated by Django 5.1.2 on 2025-01-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
