# Generated by Django 5.1.2 on 2025-01-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0002_alter_emailattachment_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='file_url',
            field=models.TextField(blank=True),
        ),
    ]
