# Generated by Django 5.1.2 on 2025-01-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0003_emailattachment_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailattachment',
            name='file_url',
        ),
    ]
