import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/src/libs/_redux/Provider";
import { QueryProvider } from "./_components/_providers/QueryProvider";
import { CurrencyProvider } from "./_components/_providers/CurrencyContext";
import { PaymentProvider } from "./_components/_providers/PaymentContext";
import { CartInitializer } from "./_components/_providers/CartInitializer";
import { WishlistInitializer } from "./_components/_providers/WishlistInitializer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ReduxProvider>
            <PaymentProvider>
              <CurrencyProvider>
                <CartInitializer />
                <WishlistInitializer />
                {children}
                <Toaster
                  position="top-right"
                  toastOptions={{
                    duration: 3000,
                    style: {
                      minWidth: "250px",
                    },
                  }}
                />
              </CurrencyProvider>
            </PaymentProvider>
          </ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
