# Generated by Django 5.1.2 on 2024-12-23 12:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currency_code_alter_currency_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, help_text='Exchange rate relative to USD (base currency)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
