# Generated by Django 5.1.2 on 2024-11-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='reference_id',
            field=models.IntegerField(help_text='ID of the related order or product', null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('order', 'New Order'), ('inventory', 'Low Stock Alert')], max_length=20),
        ),
    ]
