# Generated by Django 5.1.2 on 2025-01-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_adminnotification_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('order', 'New Order'), ('inventory', 'Low Stock Alert'), ('return_request', 'Return Request')], max_length=20),
        ),
    ]
