# Generated by Django 5.1.2 on 2025-01-19 22:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_verification_token_user_verified_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='admin/avatars'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatart_public_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
