# Generated by Django 5.1.2 on 2025-01-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_user_avatart_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatart_public_id',
            new_name='avatar_public_id',
        ),
    ]
