# Generated by Django 5.1.2 on 2025-01-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_avatart_public_id_user_avatar_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_public_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
